project:
  - proj: skyita-da-daita-test
    ph: $source_project_daita

tables:
  - table: commercial_key_number
    dataset: advertising_linear_management
    primary_key: id_commercial_key_number
  - table: customer
    dataset: advertising_linear_management
    primary_key: id_customer
  - table: organization_invoicing_pref
    dataset: advertising_linear_management
    primary_key: id_organisation
  - table: organisation
    dataset: advertising_linear_management
    primary_key: id_organisation
  - table: period
    dataset: advertising_linear_management
    primary_key: id_period
  - table: sales_prod_daypart
    dataset: advertising_linear_management
    primary_key: id_sales_product_base